### PR TITLE
Added Grid View for files

### PR DESCRIPTION
**Pull request by BraydenTW**
Hey, this solves #15.

Demo: https://www.loom.com/share/e5a3a29936d140da9a27b44b254885a4

There is a toggle feature which still allows you to open/modify folders and preview files.

### CODE REVIEW

**Review by faisalsayed10 — CHANGES_REQUESTED** [review]
Hey, thanks for the PR!

here are some inputs from me:
1. The grids look kinda too big to me, can we have the size to be somewhat similar to what the folder's size is in list view?
2. My second point is basically there's too much spacing in those grid boxes, but i think it'd be fixed when we reduce the size.
3. Can we have an icon (maybe one similar to ℹ️) in the file grids which will basically open a [drawer](https://chakra-ui.com/docs/overlay/drawer) containing file metadata and download / share options? (feel free to suggest a better approach here)

**Comment by BraydenTW** [comment]
Ok! For number 3, what if it had a similar right-click popup like with the folder item?

image

**Comment by BraydenTW** [comment]
Here is it in action: https://www.loom.com/share/89596939789f497cba4a519a79b06ec0

**Comment by faisalsayed10** [comment]
This is good actually, but i have 2 concerns right now:
1. Where do we show folder metadata? (size, etc.)
2. How can we support people who won't be able to right click? (people on ipad?) / How do we make people know that you can actually right click? (I know this is a problem for folders too)

**Comment by BraydenTW** [comment]
1. That can be added to the bottom of the ContextMenu in a simple `<Text>` tag.
2. Maybe a '...' button for a "more option"?

**Comment by BraydenTW** [comment]
How's it look now? Anything else I can fix?

image

**Comment by faisalsayed10** [comment]
Hey, This looks good functionality wise, but the buttons are bugging me, is it possible to make the buttons how they were previously?
image

(basically fully expanded, simple buttons, no border or color)

**Comment by BraydenTW** [comment]
Should be fixed now!

image

**Comment by faisalsayed10** [comment]
yooo sick, I'll review the code tomorrow and do the merge!!

**Comment by BraydenTW** [comment]
Cool, cool!

**Comment by faisalsayed10** [comment]
Hey @BraydenTW just some small change that would be good if done

can you please format all the changed files with 2 tabs instead of spaces? Currently, I'm trying to review it but it says the entire file is changed (because of spaces) and I'm not able to review the main parts

**Comment by BraydenTW** [comment]
Ok!

How exactly would I redo all those commits and have code that is changed to that tablength?

**Comment by faisalsayed10** [comment]
I'd suggest just going to the files in vs code (which have been changed), changing the indent format to `tabs - 2` and then formatting all those files and then committing

**Comment by BraydenTW** [comment]
@faisalsayed10, hmm, I did that and it looks like the original formatting style, however the editor still says I changed a lot of it.

**Comment by BraydenTW** [comment]
When I didn't even change that much. Just the lines needed.

**Comment by faisalsayed10** [comment]
@BraydenTW see this is the thing:
image

you've formatted with spaces it seems, and you'll need to change to tabs (arrows mean tabs)

**Comment by BraydenTW** [comment]
@faisalsayed10 hmm ok yeah I tried that but it is still saying I added a ton of code. 

There is no .prettierrc.js or any config for this project. You use VSCode right?

Can you share here your formatting config and how you’ve you’ve formatted firefiles?

it’s important for an open source project to have a formatting configuration file.

**Comment by faisalsayed10** [comment]
Hey yeah that's my bad, I didn't think of that. I just pushed the prettierrc file

**Comment by faisalsayed10** [comment]
I've resolved the merge conflicts too, now you can simply format your code using `yarn prettier --write .` and everything should be fixed, sorry for this.

**Comment by faisalsayed10** [comment]
@BraydenTW ^^

**Comment by BraydenTW** [comment]
Oops, sorry I'm back now. Are the changes set to be merged?

**Comment by faisalsayed10** [comment]
You just need to run `yarn --prettier write` once

**Comment by faisalsayed10** [comment]
Nice, I'll do a review soon 👍 tho will probably release it in 1.2.0 along with other stuff

**Comment by BraydenTW** [comment]
Ok @faisalsayed10, sorry for the delay.

I did exactly that but it still says I removed and added lots of code. Mainly just duplicates and stuff like that. Is this just a cumulative count over the whole PR and all its commits?

But other than that, now the formatting is all correct with tabs instead of spaces.

**Comment by faisalsayed10** [comment]
seems like you created a custom prettier config instead of what's there in the project, that might have bugged the formatting
image

**Comment by faisalsayed10** [comment]
also apparently all the files got edited somehow, i think you might have to revert the last few commits you did from here - 
image

image

**Comment by BraydenTW** [comment]
Ok, should be good now @faisalsayed10

**Comment by faisalsayed10** [comment]
Oh nice, everything looks good now

**Comment by faisalsayed10** [comment]
moved to #20

**Pull request closed without merging**
