### PR TITLE
Feature invite access

### PR DESCRIPTION
**Pull request by ConlynPattison**
# Feature - Access Control and Invites
Addresses additions and changes for Issue #17 

**Contributors:**
- Conlyn Pattison (@ConlynPattison)
- Shengzhe Zhang (@ItsBaiShiXi )
- Hien Tran (@hientrn1201)

### Additions:
- UI components and functionality for the sending, revoking, accepting, and denying access invitations
- Invitation notifications reflected through both email and in-application notifications
- Added steps of parameter validation (using the Zod library) and User authorization to both new and existing API handler functions
  - New API endpoint added for working with many-to-many `BucketsOnUsers` table
- New flow of control added for shared drives through the S3 provider (Firebase not yet implemented)
  - Shared flow removes private keys from the client and depends on signed URLs to be sent from the application server
- User roles in a drive one of Creator, Admin, Editor, or Viewer
  - Creator being the only role that can 'delete' a drive rather than simply detach
  - Creator and Admin are capable of sending and revoking user access and invitations
  - Editor is able to do all drive actions but no sharing functionality
  - Viewers can neither share nor perform writing actions on a drive
  - Role of the user and the drive name now displayed on the drive page
  - Indicator and tooltip added on the homepage for each drive to describe the user role in each drive

### Changes:
- Prisma schema changed to allow for many-to-many relation between the `User` and `Drive` tables
- Usage of Drive type and its `& keys as any` replaced with a TypeScript type `StorageDrive` allowing for better type guarding and drive type abstractions in both client and back-end
- Drives on the homepage are separated by their 'owned' or 'shared' state relative to the User

### To be addressed 100%:
- Remaining shared S3 support
  - Add support for file tagging and uploading (currently disabled in shared S3 drives)
  - TODOs written where this support is required
- Shared Firebase support
  - Add **all** support for new shared flow (currently treated as owned drives)
- Documentation to reflect these changes in Contribution and FAQ

## UI
unnamed
Figure: Shows both the access invitation icon and notification badge as well as the separation of drives either owned by or shared with the user logged in.

***

Screenshot (3)
Figure: Shows an example of the role tooltip indicator shown when hovering on each drive shown on the homepage.

***

unnamed
Figure: Shows the invitation sidebar that opens when the user interacts with the notification icon-button.

***

unnamed
Figure: Shows the modal that opens when the user interacts with the Share button. This modal’s form submission initiates the invitation of access to another user.

***

unnamed
Figure: Shows the modal popup that renders when the user interacts with the User Management MenuItem on the Actions Menu.

### Note to Reviewers
- If preferred, this PR may benefit from a squash merge as there _are_ 30+ repeated commit messages which may prompt confusion

### CODE REVIEW

**Comment by faisalsayed10** [comment]
deployment seems to be failing, please take a look
image

**Comment by ConlynPattison** [comment]
@faisalsayed10 Interesting that the error is coming up with the same version of Chakra being used, but I have put in a fix that removes the need for typing the initial theme override configuration. 

I also merged together our feature here with the additions added today with the File Tag Filtering, so there should not be additional conflicts alongside this.

Let me know if there are other changes needed.

Thank you!

**Comment by faisalsayed10** [comment]
Hi, @ConlynPattison thanks for fixing the error. I didn't see this message until after I merged another PR (#64), so now it seems that there are some more merge conflicts. Sorry about this, can you please work on fixing those, willing to help if you guys need my help

**Comment by ConlynPattison** [comment]
@faisalsayed10 Merged up the additions brought for Wasabi and Digital Ocean 👍

**Comment by faisalsayed10** [comment]
Thank you, merging now

**Review by faisalsayed10 — APPROVED** [review]
looks good to me

**Comment by faisalsayed10** [comment]
Um okay so the deployment has failed since there are many values in the production database that have the `userId` field in the `Drive` row. This PR introduces a change that removes `userId`, hence there might be data loss. So I'll need to work on this and fix it.

**Comment by faisalsayed10** [comment]
Just confirming, instead of `userId`, I will have to create a new row in my database under the table `BucketsOnUsers` right? (with the access permissions being `owner`)

**Comment by faisalsayed10** [comment]
Okay everything's fixed now. Just to confirm, can you guys head over to https://beta.firefiles.app and confirm if you guys can see all your drives properly and you are indeed the creator of those drives?

**Comment by ConlynPattison** [comment]
@faisalsayed10 Checked out the beta deployment (as well as the main build locally on my machine) and noticed there is a race condition occurring with the authentication redirect to /login and the mapping of InviteNotification.tsx and its `data`.

There is also an oversight with the Zod postDriveSchema trying to parse the being-created drive `data` (decrypted keys) parameter as a String rather than a JSON object.

Putting through a change to make the operation on InviteNotification dependent on the existence of `data` which looks to solve the issue. Also changing the schema to treat the drive `data` param as an unspecified JSON object for now, but this can be tuned with a function for better validation if desired (for checking the validity of each provider's key properties, as they vary).

**Pull request merged**
