### PR TITLE
Implement object tagging

### PR DESCRIPTION
**Pull request by nehapinni**
# Summary
Users can add, edit, and remove tags for objects within buckets if the cloud provider supports them. 
Closes Issue #44.
Authors: @alisonfung, @Cao1224, @nehapinni

# Interface 
## Row view: ​​
firefiles-taggingSystem-interface

## Grid view: 
Screenshot 2023-07-21 at 4 24 08 PM

# Implementation
TagsPopup contains the interface. A new column for tags has been added to FileRow and a Tags option has been added to the FileGrid options popover.

An enableTags boolean property and optional functions handling tags have been added to ContextValue in the useBucket hook. enableTags is defined in each cloud provider hook. This allows TagsPopup to call the appropriate tag functions for the cloud provider. If tags are not supported by the provider, enableTags will be false, the tags option will be grayed out, and the user will receive an error toast when attempting to select the tags option on either view as shown below.

Screen Shot 2023-07-21 at 4 46 43 PM
Screen Shot 2023-07-21 at 4 47 34 PM

A type Tag has been added to represent a tag with the properties key and value.

The implemented tag functions are listTags , addTags, removeTags, and editTags. addTags, removeTags, and editTags return a boolean indicating success or failure. These functions handle their own errors and display appropriate error messages using toasts. TagsPopup will display a success toast if appropriate. listTags returns an array of Tags for TagsPopup to render.

If a tag is edited, the previous tag is removed and the new tag is added. If the new tag fails to be added, the previous tag is added back.

**For Firebase:** Tagging is supported by [custom metadata](https://firebase.google.com/docs/storage/web/file-metadata), which is an object with string properties. Any string with a length supported in Javascript is allowed for keys or values. Because of this, the implementation of addTags in useFirebase prevents blank and duplicate keys for usability even though they do not throw any errors (a duplicate key overwrites the previous value). The limit for the number of tags is the number of properties allowed for an object. 

**For Amazon S3:** Tags in Amazon S3 are key-value pairs that can be attached to objects. Each object can have up to 10 tags. According to S3, the maximum key length is 128 Unicode characters, and the maximum value length is 256 Unicode characters. The combined size of all keys and values must not exceed 2 KB. If any of these errors occur while adding a tag, a toast will be displayed with the error. In addition, putting a tag with the same key throws an error, so any edits to either the key or value require the previous tag to be removed.

Keys consisting only of spaces are prevented in both of the above providers for usability. In addition, keys that would be duplicates after leading and trailing whitespace is removed are also prevented. Blank/space-only tag values are currently allowed and do not throw any errors. 

**For Backblaze and Cloudflare:** Since these providers are implemented through S3-compatible API that does not currently support tagging, tags are disabled using a boolean statement in the useS3 hook.
# Test Cases
**Success:**
- Add tag with valid key and value
- Add tag with valid key and blank value
- Edit tag, then submit with no edits
- Edit tag value to blank value
- Edit tag key to another valid tag key
- Edit tag value to another valid tag value
- Edit both tag key and value to valid values
- Delete tag

**Shows the appropriate error:**
- Add tag with blank key
- Add tag with duplicate key
- Add tag with duplicate key with added whitespace
- Add tag with invalid key 
- Add tag with invalid value
- Add tag with invalid key and invalid value
- Edit tag key to blank key
- Edit tag key to duplicate tag key
- Edit tag key to duplicate key with added whitespace
- Edit tag key to (nonblank) invalid tag key 
- Edit a tag value to invalid tag value 
- Edit tag key to invalid key and value to valid value
- Edit tag key to valid key and value to invalid value
- Edit tag key to invalid key and value to invalid value
- Add an 11th tag to an object (S3 only)
- Attempt to access tags on Backblaze 
- Attempt to access tags on Cloudflare

### CODE REVIEW

**Comment by alisonfung** [comment]
Please let us know any feedback/changes! If this is good, our team would be open to taking on the file filtering issue afterwards.

**Comment by yednapg** [comment]
Amazing work guys! @faisalsayed10 is busy for a weeks. He will let you know by 5-7 Aug.

**Review by faisalsayed10 — APPROVED** [review]
looks good to me. great work!

**Comment by faisalsayed10** [comment]
Update: I just played around with the deployed app. I am extremely impressed by this. Really really well done! @alisonfung, @Cao1224, @nehapinni

**Comment by alisonfung** [comment]
Thank you! We are continuing to work on the filtering issue!

**Pull request merged**
