### PR TITLE
Feature file sorting

### LINKED ISSUE #29: Implement file sorting
_For CodeDay Labs_

Currently, if you see, the files are randomly rendered on the screen. We must sort the files based on their properties like `name`, `size`, or `created_at`.

Above the table which renders the list of files, add a sorting dropdown with options containing the properties. When the user selects any option, sort the list of the files.

**BONUS:** Add further flexibility by allowing users to choose whether they want their files sorted in ascending or descending order.

### PR DESCRIPTION
**Pull request by ItsBaiShiXi**
Fixes #29
Added sorting menu to sort files based on Name/Size/Created date
Added ascending and descending button next to the sorting menu

### CODE REVIEW

**Review by faisalsayed10 — APPROVED** [review]
looks good to me!

**Comment by ConlynPattison** [comment]
> 

In the process of making a change to fix a bug when opening a local, empty folder. At current state, the files from the previous, non-empty folder will be shown on the list/grid once the new folder is opened. Changing this behavior such that the shown files are updated to empty when the files state from useBucket changes to null.

**Comment by faisalsayed10** [comment]
Hey, I was playing around with the sorting feature. Just noticed two things:

1. For name - Uppercase & lowercase letters are sorted separately and hence the sort isn't really as expected.

image

3. For size - The sort doesn't really seem to work. The sizes are randomly ordered even when I click the sort button.

image


Everything else is fine, hope you can address these two bugs. Thanks!

**Comment by faisalsayed10** [comment]
@ConlynPattison Awesome, make a PR when it's ready to merge :)

**Pull request merged**
